---
title: "Back and Forth with Time"
author: "Yves Dusenge"
date: "2022-09-05"
categories: [news]
---

Some reflections suited to the present provisional state of my knowledge.

Part 1.

On relativity – “How are my customary ideas of space and time related to the character of my experiences?”

A query I ponder upon from “time” to “time”, if my character is shaped by my experiences, and my experiences are composed of my body in space and time. How have my understanding of space and time evolved over time?

Principle of special relativity – finds the concept of time upon the law of propagation light.

If time is expressed in propagation of light, is being the light of the world, to be a traveler and to reach others?

what does it mean to hold the light/ be the source of the light?

“In order to give physical significance to the concept of time, processes of some kind are required which enable relations to be established between different places. It is immaterial what kind of processes one chooses for such a definition of time”

Part 2.

if the dynamics of our world is a markov process. – according to wikipedia, a markov chain is “a stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event.”

Assuming that it is true, there are only probabilities for future events conditioned on the present state of the world, what does it mean to have free will? or/and as Einsten famously said, can it be true that “God tirelessly plays dice under laws which he has himself prescribed.”?

The paradox I encounter often is, I can never be sure I know something, but I can be sure I believe something. Since knowledge is usually associated with certainty and belief with uncertainty, does knowledge lead to more belief? Or vice versa?